# https://github.com/Ezard/semantic-prs

enabled: true
commitsOnly: true
types:
  - feat
  - fix
  - docs
  - refactor
  - build
  - ci
  - ux
  - chore
  - deps
  - test
  - tests
  - perf
  - rm
scopes:
  - dev
