[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "{{rust_version}}"
authors = [
  "{{authors}}",
]
license = "Apache-2.0"
readme = "README.md"
#description = "XXXXXXXXXXXXXXX"
#repository = "https://github.com/Alorel/{{crate_name}}-rs"
keywords = []
categories = []
include = [
  "src/",
  "Cargo.toml",
]

{% if proc_macro %}
[lib]
proc-macro = true
{% endif %}

[features]

[dependencies]
{% if proc_macro %}
proc-macro2 = "1"
syn = "2"
quote = "1"
{% endif %}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "doc_cfg",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
