[template]
ignore = ["Cargo.lock"]
cargo_generate_version = ">=0.9.0"

[conditional.within_cargo_project]
ignore = [
  ".idea",
  ".github",
  ".gitattributes",
  ".gitignore",
  "LICENSE",
]

[placeholders.rust_version]
type = "string"
prompt = "Min rust version?"
default = "1.56.0"
regex = "^[0-9]\\.[0-9]{1,3}\\.[0-9]{1,3}$"

[placeholders.proc_macro]
type = "bool"
prompt = "Is this a proc macro?"
default = false
