[template]
ignore = ["Cargo.lock"]
cargo_generate_version = ">=0.9.0"

[conditional.within_cargo_project]
ignore = [
  ".idea",
  ".github",
  ".gitattributes",
  ".gitignore",
  "LICENSE",
]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]

[conditional.'license == "skip"']
ignore = ["LICENSE"]

[placeholders.github_name]
type = "string"
prompt = "GitHub username"

[placeholders.rust_version]
type = "string"
prompt = "Min rust version?"
default = "1.56.0"
regex = "^[0-9]\\.[0-9]{1,3}\\.[0-9]{1,3}$"

[placeholders.description]
type = "string"
prompt = "Project description"
default = "<<fill later>>"

[conditional.'crate_type != "bin"'.placeholders.proc_macro]
type = "bool"
prompt = "Is this a proc macro?"
default = false

[placeholders.workspace]
type = "bool"
prompt = "Is this part of a workspace?"
default = true

[placeholders.license]
type = "string"
prompt = "License"
choices = ["Apache-2.0", "skip"]

[conditional.'license != "skip"'.placeholders.license_name]
type = "string"
prompt = "Name for the license"
