[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.56.0"
authors = [
  "{{authors}}",
]
license = "Apache-2.0"
readme = "README.md"
#description = "XXXXXXXXXXXXXXX"
#repository = "https://github.com/Alorel/{{project-name}}"
keywords = []
categories = []
include = [
  "src/",
  "Cargo.toml",
]

[features]

[dependencies]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "doc_cfg",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
