[template]
ignore = ["Cargo.lock"]
cargo_generate_version = ">=0.9.0"

[conditional.within_cargo_project]
ignore = [
  ".idea",
  ".github",
  ".gitattributes",
  ".gitignore",
  "LICENSE",
]

[placeholders.rust_version]
type = "string"
prompt = "Min rust version?"
default = "1.56.0"
regex = "^[0-9]\\.[0-9]{1,3}\\.[0-9]{1,3}$"

[placeholders.description]
type = "string"
prompt = "Project description"
default = "<<fill later>>"

[placeholders.github_name]
type = "string"
prompt = "GitHub username"

[placeholders.crate_type_deep]
type = "string"
prompt = "What kind of crate is this?"
choices = ["inherit --lib or --bin", "workspace-root", "proc-macro", "macro-within-workspace"]
