{% if crate_type_deep == "workspace-root" %}
[workspace]
members = []
{% endif %}

[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "{{rust_version}}"
authors = [
  "{{authors}}",
]
license = "Apache-2.0"
readme = "README.md"
{% if description == "<<fill later>>" %}
# description = "TODO"
{% else %}
description = "{{description}}"
{% endif %}
repository = "https://github.com/{{github_name}}/{{crate_name}}-rs"
keywords = []
categories = []
include = [
  "src/",
  "Cargo.toml",
]

{% if crate_type_deep == "proc-macro" %}
[lib]
proc-macro = true
{% endif %}

[features]
default = []

[dependencies]
{% if crate_type_deep == "proc-macro" %}
proc-macro2 = "1"
quote = "1"
syn = "2"
{% else if crate_type_deep == "macro-within-workspace" %}
proc-macro2 = {workspace = true}
quote = {workspace = true}
syn = {workspace = true}
{% else if crate_type_deep == "workspace-root" %}

[workspace.dependencies]
{% endif %}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "doc_cfg",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
